### ISSUE TITLE
Miner ignores my wallet

### ISSUE THREAD

**Issue by IvanSCP** [hellcatz/hminer#2]
<img src="https://i.ibb.co/hXVM5R6/2023-03-04-201430.png" alt="2023-03-04-201430" border="0">

<img src="https://i.ibb.co/jwxMRZt/2023-03-04-201446.png" alt="2023-03-04-201446" border="0">

**Comment by hellcatz** [comment]
Make sure you are launching the miner from your run script and not by double clicking the executable directly.

**Comment by IvanSCP** [comment]
I launched the miner via the command line, it works. Thanks
