### ISSUE TITLE
--dual-user when mining in 2 pools

### ISSUE THREAD

**Issue by BitMaci** [hellcatz/hminer#9]
Hi, sometimes a pool requires a non-wallet user (ex. Nicehash > BTC address).
Could you please implement --dual-user parameter to mine in 2 pools requiring 2 different usernames/wallet address?

Thanks!

**Comment by hellcatz** [comment]
You can provide alternate address / password in URL as following scheme
`--dual-pool=stratum+ssl://WALLET.RIG:pass@host:port`
OR
`--dual-pool=stratum+tcp://WALLET.RIG@host:port`

**Comment by BitMaci** [comment]
It works, thanks bro
